//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutMe
    {
        public int id { get; set; }
        public string MeName { get; set; }
        public string MeProfile { get; set; }
        public string MeEmail { get; set; }
        public string MePhone { get; set; }
        public string MeAbout { get; set; }
    }
}
