//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İnformation
    {
        public int id { get; set; }
        public string İnfoTitle { get; set; }
        public string İnfoDescription { get; set; }
        public string İnfoLocat { get; set; }
        public string İnfoNumber { get; set; }
        public string İnfoMail { get; set; }
        public string İnfoİcon { get; set; }
    }
}
