//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevPortfolioDP : DbContext
    {
        public DevPortfolioDP()
            : base("name=DevPortfolioDP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<İnformation> İnformation { get; set; }
        public virtual DbSet<Opinion> Opinions { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesCounter> ServicesCounters { get; set; }
        public virtual DbSet<AboutMe> AboutMes { get; set; }
        public virtual DbSet<AboutSkill> AboutSkills { get; set; }
    }
}
