//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int id { get; set; }
        public string Opinionİmg { get; set; }
        public string OpinionName { get; set; }
        public string OpinionDescription { get; set; }
    }
}
