//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int id { get; set; }
        public string Portİmg { get; set; }
        public string Portİnfo { get; set; }
        public string PortCategory { get; set; }
        public Nullable<System.DateTime> PortDate { get; set; }
    }
}
