//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesCounter
    {
        public int id { get; set; }
        public string Counterİcon { get; set; }
        public string CounterNum { get; set; }
        public string CounterText { get; set; }
    }
}
